### ISSUE TITLE
Radio buttons example

### ISSUE THREAD

**Issue by rowlando** [lvl-up/page_magic#62]
If I have a pages with radio buttons:

```html
<form method="post">
  <fieldset>
    <label for="radio-1">
      <input id="radio-1" type="radio" name="radio-group" value="yes">
      Yes
    </label>
    <label for="radio-2">
      <input id="radio-2" type="radio" name="radio-group" value="no">
      No
    </label>
  </fieldset>
  <input class="button" type="submit" value="Submit">
</form>
```

Ultimately, the page object will be used in a cucumber step like:

```gherkin
And I choose 'Yes'
```

The selector must be dynamic because the options the radio button represents will change over time.

How would I represent radio buttons that have `name="radio-group"`?

**Comment by lashd** [comment]
Thanks for the question @rowlando 

As things stand you have a couple of options. (Don't miss what I've written in the comments of the code examples)

For background,  page_magic uses capybara under the hood. Using the name on it's own to find a radio button only provides partial matcher and so would return n results. 

Traditionally you would define elements on a page object like:
```ruby
class MyPage
  text_field, :username, name: 'text_field_name'
end
```
but in your example
```ruby
class MyPage
  radios, :options, name: 'radio-group'
end
```

would return the 2 results because name is not unique enough.

Where the selector needs to be dynamic page_magic lets you specify code in a block to be executed at runtime. E.g.

```ruby
class MyPage
  radios :options do |option|
    # If you were not using labels or id's that could be derived, then you could use an xpath selector to match on the value instead.
    selector label: option
  end
end
```

This would let you write something like:

```ruby
session.visit(HomePage) #specify url: 'your url' if you are not using page mappings
session.options('Yes').set(true)
```

This will then select the radio button for you

If this is an element that is going to appear on many pages you could abstract it as follows
```ruby
class Options < PageMagic::Element
  radios :option do |option|
    selector label: option
  end

  def choose option
    self.option(option).set(true)
  end
end

class MyPage
  include PageMagic
  element Options, css: 'fieldset'
end
```

In the example above, I have created a custom element that can be put on to any page class and have used the `css: 'fieldset'` to bind it to the example you gave.

This can then be access by using:
```ruby
session.options.choose('Yes')
```

You will note that I added a helper method in to the custom element to 'dry' up the code and remove the need for typing `.set(true)`.

In terms of whether there is anything that page_magic could do out of the box, it's something we could definitely look at. It really depends on if we can think of a method that will always find the required radio irrespective of whether it has a label or not etc...

Hope this helps and let me know how you get on.

**Comment by rowlando** [comment]
Thanks @lashd.

Your examples have given a better understanding about how to use page magic in general. More of this please!

I went for the delegation option in the end.

**Comment by lashd** [comment]
Thanks @rowlando, regarding this particular issue, would the following have helped any?

https://github.com/lvl-up/page_magic#interacting-with-elements
